added rm command, added better ssh remote support

diff --git a/bin/git-xfer-add b/bin/git-xfer-add
--- a/bin/git-xfer-add
+++ b/bin/git-xfer-add
@@ -16,12 +16,16 @@ usage() {
 # exec
 # ----
 add(){
-    if [ -e "$1" ]; then
-        shasum=`sha1sum "$1" | awk '{ print $1 }'`
-        fname=`echo "$1" | sed "s|$base|.|"`
-        if [ ! `grep "$fname  " $cache | wc -l` -gt 0 ]; then
-            echo "$shasum  $fname  local" >> "$cache"
-        fi
+    if [ ! -e "$1" ]; then
+        echo 'File to not found!'
+        exit 1
+    fi
+
+    shasum=`sha1sum "$1" | awk '{ print $1 }'`
+    fname=`echo "$1" | sed "s|$base|.|"`
+    if [ ! `grep "$fname  " $cache | wc -l` -gt 0 ]; then
+        echo "$shasum  $fname  local" >> "$cache"
+        echo "$fname" >> "$base/.gitignore"
     fi
 }
 
diff --git a/bin/git-xfer-pull b/bin/git-xfer-pull
--- a/bin/git-xfer-pull
+++ b/bin/git-xfer-pull
@@ -28,28 +28,68 @@ main() {
             ;;
     esac
 
-    port="22"
     case "$1" in
         "-p"|"--port")
             port="$2";
             ;;
     esac
 
+    # verify remote
+    remote=`git remote -v | grep "$dest\s" | awk '{ print $2 }' | uniq | sed 's/\.git$//'`
+    if [ ! "$remote" ]; then
+        echo 'cannot find remote -- try git remote add <remote> <url>'
+    fi
+
+    # handle ssh url type
+    if [ `echo "$remote" | grep 'ssh://'` ]; then
+        urlstring=`echo "$remote" | sed 's|ssh://||' | sed 's|:|  |' | sed 's|/|  /|'`
+        url=`echo "$urlstring" | awk '{ print $1 }'`
+        if [ ! `echo "$urlstring" | awk '{ print $3 }'` ]; then
+            port="22"
+            repo=`echo "$urlstring" | awk '{ print $2 }'`
+        else
+            port=`echo "$urlstring" | awk '{ print $2 }'`
+            repo=`echo "$urlstring" | awk '{ print $3 }'`
+        fi
+
+    # don't allow operations to github (they have git-lfs)
+    elif [ `echo "$remote" | grep 'github.com'` ]; then
+        echo 'Syncing with GitHub is not supported!'
+        exit 1
+
+    # ssh specification without port
+    elif [ `echo "$remote" | grep '@' | grep ':'` ]; then
+        url=`echo "$remote" | sed 's|:|  |' | awk '{ print $1 }'`
+        port="22"
+        repo=`echo "$remote" | sed 's|:|  |' | awk '{ print $2 }'`
+    
+    # local repo
+    else
+        repo="$remote"
+    fi
+
+    # do the copying
     cd "$base"
-    url=`git remote -v | grep $dest | awk '{ print $2 }' | uniq | sed 's/\.git$//'`
-    if [ $url ]; then
-        remote=`echo "$url" | sed 's/:/  /' | awk '{ print $1 }'`
-        remotedest=`echo "$url" | sed 's/:/  /' | awk '{ print $2 }'`
-        for file in `ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$remote" "cd $remotedest; git xfer list -f"`; do
+    if [ -z $port ]; then
+        # local repo
+        for file in `cd "$repo" && git xfer list -f`; do
+            cd "$base"
             if [ ! -e "$file" ]; then
-                rsync -avz -e "ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress "$url/$file" "$file"
+                rsync -avz --progress "$repo/$file" "$file"
                 git xfer add "$file"
             fi
         done
     else
-        echo 'cannot find remote -- try git remote add <remote> <url>'
+        # remote repo
+        for file in `ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$url" "cd $repo; git xfer list -f"`; do
+            if [ ! -e "$file" ]; then
+                rsync -avz -e "ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress "$url:$repo/$file" "$file"
+                git xfer add "$file"
+            fi
+        done
     fi
 
+    exit 0
 }
 
 base=`git rev-parse --show-toplevel`
diff --git a/bin/git-xfer-push b/bin/git-xfer-push
--- a/bin/git-xfer-push
+++ b/bin/git-xfer-push
@@ -28,28 +28,67 @@ main() {
             ;;
     esac
 
-    port="22"
     case "$1" in
         "-p"|"--port")
-			port="$2";
-			;;
-	esac
+            port="$2";
+            ;;
+    esac
 
-    cd "$base"
-    url=`git remote -v | grep $dest | awk '{ print $2 }' | uniq | sed 's/\.git$//'`
-    if [ $url ]; then
-        for file in `grep -v ",$dest" "$cache" | awk '{ print $2 }'`; do
-			rsync -avz -e "ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress "$file" "$url/$file"
-			remote=`echo "$url" | sed 's/:/  /' | awk '{ print $1 }'`
-			remotedest=`echo "$url" | sed 's/:/  /' | awk '{ print $2 }'`
-			ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$remote" "cd $remotedest; git xfer add \"$file\""
-			grep -v "$file  " "$cache" > "$cache.lck"
-			echo `grep "$file  " "$cache" | sed "s|,$dest||"`,$dest >> "$cache.lck"
-			mv "$cache.lck" "$cache"
-        done
-    else
-    	echo 'cannot find remote -- try git remote add <remote> <url>'
+    # verify remote
+    remote=`git remote -v | grep "$dest\s" | awk '{ print $2 }' | uniq | sed 's/\.git$//'`
+    if [ ! "$remote" ]; then
+        echo 'cannot find remote -- try git remote add <remote> <url>'
     fi
+
+    # handle ssh url type
+    if [ `echo "$remote" | grep 'ssh://'` ]; then
+        urlstring=`echo "$remote" | sed 's|ssh://||' | sed 's|:|  |' | sed 's|/|  /|'`
+        url=`echo "$urlstring" | awk '{ print $1 }'`
+        if [ ! `echo "$urlstring" | awk '{ print $3 }'` ]; then
+            port="22"
+            repo=`echo "$urlstring" | awk '{ print $2 }'`
+        else
+            port=`echo "$urlstring" | awk '{ print $2 }'`
+            repo=`echo "$urlstring" | awk '{ print $3 }'`
+        fi
+
+    # don't allow operations to github (they have git-lfs)
+    elif [ `echo "$remote" | grep 'github.com'` ]; then
+        echo 'Syncing with GitHub is not supported!'
+        exit 1
+
+    # ssh specification without port
+    elif [ `echo "$remote" | grep '@' | grep ':'` ]; then
+        url=`echo "$remote" | sed 's|:|  |' | awk '{ print $1 }'`
+        port="22"
+        repo=`echo "$remote" | sed 's|:|  |' | awk '{ print $2 }'`
+    
+    # local repo
+    else
+        repo="$remote"
+    fi
+
+    # do the copying
+    cd "$base"
+    for file in `grep -v ",$dest" "$cache" | awk '{ print $2 }'`; do
+		# copy locally
+        if [ -z $port ]; then
+            rsync -avz --progress "$file" "$repo/$file"
+            cd "$repo" && git xfer add "$file" && cd "$base"
+        
+        # copy over ssh
+        else
+            rsync -avz -e "ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress "$file" "$url:$repo/$file"
+    		ssh -p $port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "$url" "cd $repo; git xfer add \"$file\""
+        fi
+
+        # update cache
+		grep -v "$file  " "$cache" > "$cache.lck"
+		echo `grep "$file  " "$cache" | sed "s|,$dest||"`,$dest >> "$cache.lck"
+		mv "$cache.lck" "$cache"
+    done
+
+    exit 0
 
 }
 
