added syncing capabilities

diff --git a/test/test-local b/test/test-local
--- a/test/test-local
+++ b/test/test-local
@@ -14,6 +14,7 @@ cd "$base/test"
 testdir=/tmp/git-xfer-testing-local
 rm "$cache"
 touch "$cache"
+rm -rf "$testdir"
 mkdir -p "$testdir"
 cp -r "$base" "$testdir/"
 if [ ! `git remote | grep "testserver"` ]; then
@@ -25,6 +26,9 @@ fi
 # -----
 clean() {
     cd "$base/test"
+    if [ `git branch | grep 'testing' | wc -l` -eq 1 ]; then
+        git branch -d testing
+    fi
     rm -f test-local-file test-remote-file
     git remote remove testserver
     rm -rf "$testdir"
@@ -38,16 +42,21 @@ clean() {
 # add
 git xfer add test-local test-remote
 shasum=`sha1sum test-local | awk '{ print $1 }'`
+echo -n 'add ........................... '
 if [ `cat "$cache" | grep "$shasum" | wc -l` -ne 1 ]; then
     echo 'Fail! Error adding files.'
+    clean
     exit 1
 fi
 if [ `cat "$cache" | wc -l` -ne 2 ]; then
     echo 'Fail! Error adding files.'
+    clean
     exit 1
 fi
+echo 'ok'
 
 # list
+echo -n 'list .......................... '
 if [ `git xfer list | wc -l` -ne 2 ]; then
     echo 'Fail! Error listing files.'
     exit 1
@@ -56,21 +65,43 @@ git xfer list -v > "$cache.tst"
 if [ `diff "$cache.tst" "$cache" | wc -l` -ne 0 ]; then
     echo 'Fail! Error listing verbose.'
     rm "$cache.tst"
+    clean
     exit 1
 fi
 rm "$cache.tst"
+echo 'ok'
 
 # remove
+echo -n 'remove ........................ '
 git xfer remove test-local test-remote
 if [ `cat "$cache" | wc -l` -ne 0 ]; then
     echo 'Fail! Error removing files.'
+    clean
     exit 1
 fi
+echo 'ok'
+
+# sync
+echo -n 'sync .......................... '
+cd "$testdir"/git-xfer/
+git branch testing
+git checkout testing
+cd "$base/test"
+git xfer sync testserver master
+cd "$testdir"/git-xfer/test
+if [ `git branch | grep '* master' | wc -l` -ne 1 ]; then
+    echo 'Sync failed!';
+    clean
+    exit 1
+fi
+echo 'ok'
 
 # push
+echo -n 'push .......................... '
+cd "$base/test"
 echo 'test' > test-local-file
 git xfer add test-local-file
-git xfer push testserver
+git xfer push testserver 2>&1 1>/dev/null
 cd "$testdir"/git-xfer/test
 if [ ! -e "test-local-file" ]; then
     echo "Fail! Cannot push files to remote."
@@ -88,8 +119,10 @@ if [ `git xfer list | grep "test-local-file" | grep "testserver" | wc -l` -ne 1 
     clean
     exit 1
 fi
+echo 'ok'
 
 # pull
+echo 'pull .......................... '
 cd "$testdir/git-xfer/test"
 echo 'test' > test-remote-file
 git xfer add test-remote-file
@@ -105,7 +138,10 @@ if [ `git xfer list | grep "test-remote-file" | wc -l` -ne 1 ]; then
     clean
     exit 1
 fi
+echo 'ok'
+
+echo -n 'clean ......................... '
 git xfer rm test-local-file
 git xfer rm test-remote-file
-
 clean
+echo 'ok'
diff --git a/test/test-remote b/test/test-remote
--- a/test/test-remote
+++ b/test/test-remote
@@ -25,6 +25,9 @@ fi
 # -----
 clean() {
     cd "$base/test"
+    if [ `git branch | grep 'testing' | wc -l` -eq 1 ]; then
+        git branch -d testing
+    fi
     rm -f test-local-file test-remote-file
     git remote remove testserver
     rm -rf "$testdir"
@@ -35,7 +38,23 @@ clean() {
 
 # testing
 # -------
+echo -n 'sync .......................... '
+cd "$testdir"/git-xfer/
+git branch testing
+git checkout testing
+cd "$base/test"
+git xfer sync testserver master
+cd "$testdir"/git-xfer/test
+if [ `git branch | grep '* master' | wc -l` -ne 1 ]; then
+    echo 'Sync failed!';
+    clean
+    exit 1
+fi
+echo 'ok'
+
 # push
+echo -n 'push .......................... '
+cd "$base/test"
 echo 'test' > test-local-file
 git xfer add test-local-file
 git xfer push testserver
@@ -58,6 +77,7 @@ if [ `git xfer list | grep "test-local-file" | grep "testserver" | wc -l` -ne 1 
 fi
 
 # pull
+echo -n 'pull .......................... '
 cd "$testdir/git-xfer/test"
 echo 'test' > test-remote-file
 git xfer add test-remote-file
@@ -74,7 +94,8 @@ if [ `git xfer list | grep "test-remote-file" | wc -l` -ne 1 ]; then
     exit 1
 fi
 
+echo -n 'clean ......................... '
 git xfer rm test-local-file
 git xfer rm test-remote-file
-
 clean
+echo 'ok'
