changed paradigm for how subcommands are evoked, added utilities file with common functions

diff --git a/test/test b/test/test
--- a/test/test
+++ b/test/test
@@ -12,6 +12,7 @@ CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 BASE=`git rev-parse --show-toplevel`
 CACHE="$BASE/.git/xfer/cache"
 TSANDBOX="$CWD/sandbox"
+ERRORS=""
 
 
 # funcs
@@ -30,8 +31,8 @@ usage() {
 }
 
 clean() {
-    # remove testing files
-    # rm -rf $TSANDBOX
+    #remove testing files
+    rm -rf $TSANDBOX
 
     # clear remotes and branches
     if [ `git remote | grep 'testserver' | wc -l` -eq 1 ]; then
@@ -48,9 +49,9 @@ clean() {
 
 create() {
     dir=`dirname "$1"`
-    if [ "$dir" == "." ]; then
-        
-    mkdir -p "$dir"
+    if [ "$dir" != "." ]; then
+        mkdir -p "$dir"
+    fi
     echo "$1" > "$1"
 }
 
@@ -63,6 +64,7 @@ assertEqual() {
         printf $GREEN'✓'$NC
     else
         printf $RED'✗'$NC
+        ERRORS="$ERRORS\n$1 is not equal to $2!"
         FAIL='TRUE'
     fi
 }
@@ -75,6 +77,7 @@ assertContains() {
         printf $GREEN'✓'$NC
     else
         printf $RED'✗'$NC
+        ERRORS="$ERRORS\n$1 does not contain $2!"
         FAIL='TRUE'
     fi
 }
@@ -85,9 +88,23 @@ assertNotContains() {
     NC='\033[0m'
     if [ `cat "$1" | grep "$2" | wc -l` -gt 0 ]; then
         printf $RED'✗'$NC
+        ERRORS="$ERRORS\n$1 contains $2 when it should not!"
         FAIL='TRUE'
     else
         printf $GREEN'✓'$NC
+    fi
+}
+
+assertExists() {
+    GREEN='\033[0;32m'
+    RED='\033[0;31m'
+    NC='\033[0m'
+    if [ -e "$1" ]; then
+        printf $GREEN'✓'$NC
+    else
+        printf $RED'✗'$NC
+        ERRORS="$ERRORS\n$1 does not exist!"
+        FAIL='TRUE'
     fi
 }
 
@@ -115,12 +132,18 @@ fi
 
 if [ -e "$CWD/test-$1" ]; then
     mkdir -p "$TSANDBOX"
-    pushd "$TSANDBOX"
+    pushd "$TSANDBOX" 2>&1 1>/dev/null
     source "$CWD/test-$1"
-    popd
+    popd 2>&1 1>/dev/null
 fi
 
 
 # clean
 # -----
 clean
+if [ $FAIL == "TRUE" ]; then
+    echo ""
+    echo "Errors captured during testing: "
+    printf "$ERRORS\n"
+    exit 1
+fi
