fixed push/pull git xfer issues

diff --git a/test/test-local b/test/test-local
--- a/test/test-local
+++ b/test/test-local
@@ -174,11 +174,24 @@ printf 'ok\n'
 # push
 printf 'push .......................... '
 cd "$base/test"
+mkdir -p space\ test
 echo 'test' > test-local-file
-git xfer add test-local-file
-git xfer push testserver 2>&1 1>/dev/null
+echo 'test' > test-file\ withspace
+echo 'test' > space\ test/test-file
+git xfer add test-local-file test-file\ withspace space\ test/test-file
+git xfer push testserver
 cd "$testdir"/git-xfer/test
 if [ ! -e "test-local-file" ]; then
+    echo "Fail! Cannot push files to remote."
+    clean
+    exit 1
+fi
+if [ ! -e "test-file withspace" ]; then
+    echo "Fail! Cannot push files to remote."
+    clean
+    exit 1
+fi
+if [ ! -e "space test/test-file" ]; then
     echo "Fail! Cannot push files to remote."
     clean
     exit 1
@@ -188,25 +201,49 @@ if [ `git xfer list | grep "test-local-file" | wc -l` -ne 1 ]; then
     clean
     exit 1
 fi
-git xfer rm test-local-file
+if [ `git xfer list | grep "withspace" | wc -l` -ne 1 ]; then
+    echo "Fail! Remote not synced."
+    clean
+    exit 1
+fi
+if [ `git xfer list | grep "space.*test-file" | wc -l` -ne 1 ]; then
+    echo "Fail! Remote not synced."
+    clean
+    exit 1
+fi
+git xfer rm test-local-file test-file\ withspace space\ test/test-file
 cd "$base/test"
 if [ `git xfer list | grep "test-local-file" | grep "testserver" | wc -l` -ne 1 ]; then
     echo "Fail! Local not synced with transfer status."
     clean
     exit 1
 fi
-git xfer rm test-local-file
+git xfer rm test-local-file test-file\ withspace space\ test/test-file
+rm -rf space\ test
 printf 'ok\n'
 
 # pull
 echo 'pull .......................... '
 cd "$testdir/git-xfer/test"
+mkdir -p space\ test
 echo 'test' > test-remote-file
-git xfer add test-remote-file
+echo 'test' > test-file\ withspace
+echo 'test' > space\ test/test-file
+git xfer add test-remote-file test-file\ withspace space\ test/test-file
 cd "$base/test"
 git xfer pull testserver
 if [ ! -e "test-remote-file" ]; then
-    echo "Fail! Cannot pull remote files."
+    echo "Fail! Cannot push files to remote."
+    clean
+    exit 1
+fi
+if [ ! -e "test-file withspace" ]; then
+    echo "Fail! Cannot push files to remote."
+    clean
+    exit 1
+fi
+if [ ! -e "space test/test-file" ]; then
+    echo "Fail! Cannot push files to remote."
     clean
     exit 1
 fi
@@ -215,7 +252,18 @@ if [ `git xfer list | grep "test-remote-file" | wc -l` -ne 1 ]; then
     clean
     exit 1
 fi
-git xfer rm test-remote-file
+if [ `git xfer list | grep "withspace" | wc -l` -ne 1 ]; then
+    echo "Fail! Local not synced."
+    clean
+    exit 1
+fi
+if [ `git xfer list | grep "space.*test-file" | wc -l` -ne 1 ]; then
+    echo "Fail! Local not synced."
+    clean
+    exit 1
+fi
+git xfer rm test-remote-file test-file\ withspace space\ test/test-file
+rm -rf space\ test
 printf 'ok\n'
 
 printf 'clean ......................... '
